# Generated by Django 6.1.1 on 2026-10-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_output_result_generationtask_output_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1:1 (Square)', max_length=30),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='cfg',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='negative_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='pod_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='seed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='status_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='steps',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Deploying Pod...'), ('DOWNLOADING', 'Downloading Models...'), ('GENERATING', 'Processing ComfyUI...'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
